### ISSUE TITLE
Separating queries and type defs with codegen

### ISSUE THREAD

**Issue by jregistr** [d4rekanguok/gatsby-typescript#97]
Hello!
Using the `gatsby-plugin-graphql-codegen` plugin, is it possible to create separate files for types and queries?
Let's say I'd like all the types to be in a *graphql-types.ts* and *graphql-queries.ts*. In previous non gatsby projects using the codegen app standalone, I've done this using *generates* config. Something like this:
```yaml
schema:
  - https://api.github...
generates:
  gql-types.ts:
    plugins:
      - typescript
  gql-queries.ts:
    documents:
      - 'src/**/*.ts'
    preset: import-types
    presetConfig:
      typesPath: ./gql-types
    plugins:
      - typescript-operations
```

I've tried adding an *additionalSchema* gatsby plugin option only pointing it to the tsx files. This doesn't seem to work.

Is this possible w/ the plugin as is?
